services:
  frontend:
    build:
      context: ./my-app
      dockerfile: ./docker/Dockerfile
      args:
        - REACT_APP_BACKEND_API_URL=${REACT_APP_BACKEND_API_URL}
        - REACT_APP_WS_API_URL=${REACT_APP_WS_API_URL}
    image: tonytry/project-frontend:latest
    ports:
      - "3000:8080" 
    depends_on:
      - backend
    env_file:
      - ./my-app/.env

  
  backend:
    build:
      context: ./node_runtime
      dockerfile: ./docker/Dockerfile
    image: tonytry/project-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./node_runtime/.env
